### ISSUE TITLE
Released binary issue?

### ISSUE THREAD

**Issue by NikosGavalas** [gmantaos/Goirate#1]
The released binary goirate.linux.amd64, v0.10.0, is dynamically linked. I don't know if this was intended.
```
$  file goirate 
goirate: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, not stripped
$ ldd goirate 
	linux-vdso.so.1 (0x00007ffdf81ac000)
	libc.musl-x86_64.so.1 => not found
```

Related: https://github.com/mitchellh/gox/issues/55 https://github.com/docker-library/golang/issues/152

**Comment by gmantaos** [comment]
Thanks for the issue. Should be statically linked as of [10.0.1](https://github.com/gmantaos/Goirate/releases).
